[package]
name = "prime"
version = "0.2.5"
edition = "2021"

[dependencies]
num-complex = "0.4.2"
num-bigint =  { version = "0.4.3", features = ["rand"] }
num-prime = { version = "0.4.1", features=["big-int", "big-table"] }
num-iter = "0.1.43"
num-traits = "0.2.4"
rayon = "1.5.3"
clap = { version = "3.2.16", features = ["derive"] }
rand = "0.8.5"
astro-float = "0.5.0"
num-modular = "0.5.1"
indicatif = "0.17.3"
number-theory = "0.0.19"
